### ISSUE TITLE
Any other way to get data, rather than globus?

### ISSUE THREAD

**Issue by kingaza** [VLOGroup/mri-variationalnetwork#1]
Hello @khammernik ,

Amazing work!
I have some problem of globus here and I can't download the training data. 
Is there any other method to get the data, or how can I use my own data?
Thanks a lot.

Best Regards,
Kingaza

**Comment by khammernik** [comment]
Hi @kingaza!

What exactly is the problem with the globus access? Due to the large memory requirement of the data, we cannot host it in a different way. Some more details about the data can be found [here](http://cai2r.net/resources/software/one-hundred-knee-mri-cases).

You can of course use your own data. Therefore, you have to adapt the `VnMriReconstructionData` class in `mridata.py` accordingly. The necessary inputs are defined as placeholders in lines 145-156. While u, target, and sampling mask have the format [N, nFE, nPE], rawdata and sensitivities have the format [N, nCh, nFE, nPE] where N is the number of samples, nCh is the number of coils, nFE is the number of frequency encoding lines and nPE is the number of phase encoding lines.

Best regards,
Kerstin

**Comment by yinhaoz** [comment]
Also can't access the data, error msg from Globus:

Denied by endpoint, Command Failed: Error (list) Endpoint: NYULH Radiology Reconstruction Data (92ca2774-5225-11e8-9056-0a6d4e044368) Server: dtn1.nyumc.org:2811 Command: MLST / Message: Fatal FTP Response --- Details: 550-GlobusError: v=1 c=PERMISSION_DENIED\r\n550-GridFTP-Errno: 13\r\n550-GridFTP-Reason: System error in stat\r\n550-GridFTP-Error-String: Permission denied\r\n550 End.\r\n

**Comment by jtamir** [comment]
Hi, you can access most of the data here: http://mridata.org/list?project=NYU%20machine%20learning%20data

**Comment by kingaza** [comment]
Thanks @khammernik @jtamir .
You both really help!
